# Default values for ui helm chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
maxUnavailable: 0

image:
  repository: hypertrace/hypertrace-ui
  pullPolicy: IfNotPresent

imagePullSecrets: []

containerPort: 80

service:
  type: ClusterIP
  port: 80

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
   limits:
     cpu: 0.5
     memory: 128Mi
   requests:
     cpu: 50m
     memory: 64Mi

podLabels:
  app: hypertrace-ui

deploymentSelectorMatchLabels:
  app: hypertrace-ui

serviceSelectorLabels:
  app: hypertrace-ui

###########
# Config Maps
###########
nginxConfig:
  name: hypertrace-nginx-config
  ## Used in hypertrace standalone deployment to reuse nginx
  graphqlRedirectEnabled: false
  graphqlHost: hypertrace-graphql-service
  graphqlPort: 23431
